# Generated by Django 5.2.8 on 2025-12-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0005_category_is_active_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
    ]
