# Generated by Django 5.2.8 on 2026-01-17 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0007_size_alter_user_date_joined_product_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('season', models.CharField(max_length=50, verbose_name='Сезон')),
                ('material_outer', models.CharField(max_length=255, verbose_name='Материал верха')),
                ('material_inner', models.CharField(max_length=255, verbose_name='Материал подкладки')),
                ('material_sole', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал подошвы')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='xwear.product', verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Характеристики товара',
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
    ]
