# Generated by Django 5.2.8 on 2026-01-25 17:38

import easy_thumbnails.fields
import xwear.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0009_brand_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='slider/', validators=[xwear.utils.validate_banner_image], verbose_name='Изображение (min 1540x630)')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order', '-id'],
            },
        ),
    ]
