# Generated by Django 5.2.8 on 2026-04-09 14:42

import django.core.validators
import django.db.models.deletion
import easy_thumbnails.fields
import mptt.fields
import xwear.utils
import xwear.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название цвета')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('hex_code', models.CharField(default='#000000', help_text='Обязательно для однотонных и двухцветных', max_length=7, verbose_name='Основной HEX-код')),
                ('hex_code_2', models.CharField(blank=True, help_text='Заполните для двухцветных товаров (например, черно-белый)', max_length=7, verbose_name='Дополнительный HEX')),
                ('texture', models.ImageField(blank=True, help_text='Загрузите картинку (например, камуфляж). Если загружена, HEX-коды игнорируются.', upload_to='color_textures/', verbose_name='Текстура (Паттерн)')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Размер')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SliderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=xwear.utils.UploadToPath('banner', 'slide'), validators=[xwear.validators.ImageValidator(max_mb=2.0, min_height=630, min_width=1540)], verbose_name='Изображение (min 1540x630, max 2Мб)')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('singular_name', models.CharField(blank=True, default='', help_text='Оставьте пустым, если совпадает с основным названием или не требуется', max_length=30, verbose_name='Название (ед. ч.)')),
                ('slug', models.SlugField(blank=True, max_length=30, verbose_name='Слаг')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='xwear.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('material_type', models.CharField(choices=[('OUTER', 'Верх'), ('INNER', 'Подкладка'), ('SOLE', 'Подошва')], max_length=10, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'unique_together': {('name', 'material_type')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Оставьте пустым, для автогенерации из категории', max_length=50, verbose_name='Вид товара')),
                ('model_name', models.CharField(max_length=50, verbose_name='Модель')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Унисекс')], max_length=1, verbose_name='Пол')),
                ('season', models.CharField(choices=[('WINTER', 'Зима'), ('SUMMER', 'Лето'), ('AUTUMN_SPRING', 'Демисезон'), ('ALL_SEASON', 'Всесезонный')], max_length=20, verbose_name='Сезон')),
                ('description', models.TextField(blank=True, verbose_name='Общее описание')),
                ('slug', models.SlugField(blank=True, help_text='Генерируется автоматически на основе вида, бренда и модели', max_length=150, unique=True, verbose_name='Слаг базовой модели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='xwear.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='xwear.category', verbose_name='Категория')),
                ('available_sizes', models.ManyToManyField(blank=True, help_text='Этот перечень размеров будет автоматически добавляться при создании новых цветов (вариантов) товара.', to='xwear.size', verbose_name='Размерная сетка')),
            ],
            options={
                'verbose_name': 'Базовый товар',
                'verbose_name_plural': 'Базовые товары',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, help_text="Генерируется автоматически '[BRAND(2)][GENDER(1)][CAT_ID(3)]-[PROD_ID(5)][RAND(3)]'", max_length=50, unique=True, verbose_name='Артикул')),
                ('slug', models.SlugField(blank=True, help_text='Генерируется автоматически на основе вида, бренда, модели и цвета', max_length=200, unique=True, verbose_name='Слаг варианта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='xwear.color', verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='xwear.product', verbose_name='Базовая модель')),
            ],
            options={
                'verbose_name': 'Ассортимент',
                'verbose_name_plural': 'Ассортимент',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_inner', models.ForeignKey(blank=True, limit_choices_to={'material_type': 'INNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_material', to='xwear.material', verbose_name='Материал подкладки')),
                ('material_outer', models.ForeignKey(limit_choices_to={'material_type': 'OUTER'}, on_delete=django.db.models.deletion.PROTECT, related_name='outer_material', to='xwear.material', verbose_name='Материал верха')),
                ('material_sole', models.ForeignKey(blank=True, limit_choices_to={'material_type': 'SOLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sole_material', to='xwear.material', verbose_name='Материал подошвы')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='xwear.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Состав товара',
                'verbose_name_plural': 'Составы товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=xwear.utils.UploadToPath('products', use_category_subdir=True), validators=[xwear.validators.ImageValidator(max_mb=1.5, min_height=490, min_width=670)], verbose_name='Фото (min 670x490, max 1,5Мб)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('alt', models.CharField(blank=True, help_text='Оставьте пустым для автогенерации', max_length=200, verbose_name='Alt текст')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='xwear.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='xwear.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка %')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Итоговая цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='В наличии')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='xwear.productvariant', verbose_name='Вариант товара')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwear.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер/цена товара',
                'verbose_name_plural': 'Размеры/цены товаров',
                'ordering': ['size'],
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='xwear_produ_product_a8f8d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'variant')},
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['variant', 'is_active'], name='xwear_produ_variant_74b453_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('variant', 'size')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='xwear_produ_is_acti_5775a5_idx'),
        ),
    ]
