# Generated by Django 5.2.8 on 2026-03-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Итоговая цена'),
        ),
    ]
