# Generated by Django 5.2.8 on 2026-03-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0002_productsize_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='xwear.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='article',
            field=models.CharField(blank=True, help_text='Оставьте пустым для автогенерации (BRAND-CAT-ID-RANDOM) или введите вручную.', max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='season',
            field=models.CharField(choices=[('WINTER', 'Зима'), ('SUMMER', 'Лето'), ('AUTUMN_SPRING', 'Демисезон'), ('ALL_SEASON', 'Всесезонный')], max_length=20, verbose_name='Сезон'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('material_type', models.CharField(choices=[('OUTER', 'Материал верха'), ('INNER', 'Материал подкладки'), ('SOLE', 'Материал подошвы')], max_length=10, verbose_name='Тип материала')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'unique_together': {('name', 'material_type')},
            },
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='material_inner',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_type': 'INNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_material', to='xwear.material', verbose_name='Материал подкладки'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='material_outer',
            field=models.ForeignKey(limit_choices_to={'material_type': 'OUTER'}, on_delete=django.db.models.deletion.PROTECT, related_name='outer_material', to='xwear.material', verbose_name='Материал верха'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='material_sole',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_type': 'SOLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sole_material', to='xwear.material', verbose_name='Материал подошвы'),
        ),
    ]
