# Generated by Django 5.2.8 on 2026-04-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0002_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position'], 'verbose_name': 'Фото варианта', 'verbose_name_plural': 'Фото варианта'},
        ),
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'verbose_name': 'Материал варианта', 'verbose_name_plural': 'Материалы варианта'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['size'], 'verbose_name': 'Размер/цена варианта', 'verbose_name_plural': 'Размеры/цены варианта'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Ассортимент', 'verbose_name_plural': 'Ассортимент'},
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, help_text='Этот перечень размеров будет автоматически добавляться при создании новых вариантов товара.', to='xwear.size', verbose_name='Размеры'),
        ),
    ]
