# Generated by Django 5.2.8 on 2026-04-13 14:04

import django.utils.timezone
import easy_thumbnails.fields
import xwear.utils
import xwear.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0003_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Состав'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['size'], 'verbose_name': 'Размер и цена', 'verbose_name_plural': 'Размеры и цены (Сохраните товар для автоматического проставления размеров)'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=xwear.utils.UploadToPath('products', use_category_subdir=True), validators=[xwear.validators.ImageValidator(max_mb=1.5, min_height=600, min_width=500)], verbose_name='Фото (min 500x600, max 1,5Мб)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
