# Generated by Django 5.2.8 on 2026-03-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0004_alter_productimage_options_productimage_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position'], 'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('OUTER', 'Верх'), ('INNER', 'Подкладка'), ('SOLE', 'Подошва')], max_length=10, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, help_text='Оставьте пустым для автогенерации', max_length=200, verbose_name='Alt текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
