# Generated by Django 5.2.8 on 2026-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0004_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
