# Generated by Django 5.2.8 on 2026-03-11 15:26

import easy_thumbnails.fields
import xwear.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0005_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=xwear.utils.UploadToPath('products'), verbose_name='Фото'),
        ),
    ]
