# Generated by Django 5.2.8 on 2026-04-14 10:34

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0005_alter_productvariant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
