# Generated by Django 5.2.8 on 2026-04-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Генерируется автоматически на основе вида, бренда и модели', max_length=150, verbose_name='Слаг базовой модели'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('slug', 'category'), name='unique_product_slug_per_category'),
        ),
    ]
