# Generated by Django 5.2.8 on 2026-03-13 18:24

import easy_thumbnails.fields
import xwear.utils
import xwear.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=xwear.utils.UploadToPath('products'), validators=[xwear.validators.ImageValidator(max_mb=1.5, min_height=490, min_width=670)], verbose_name='Фото (min 670x490, max 1,5Мб)'),
        ),
    ]
