# Generated by Django 5.2.8 on 2026-04-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0007_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(blank=True, help_text='Генерируется автоматически на основе вида, бренда, модели и цвета', max_length=200, verbose_name='Слаг варианта'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('slug', 'product'), name='unique_variant_slug_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color'), name='unique_product_color_variant'),
        ),
    ]
