# Generated by Django 5.2.8 on 2026-03-15 14:23

import easy_thumbnails.fields
import xwear.utils
import xwear.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0007_alter_product_name_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderbanner',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=xwear.utils.UploadToPath('products', use_category_subdir=True), validators=[xwear.validators.ImageValidator(max_mb=1.5, min_height=490, min_width=670)], verbose_name='Фото (min 670x490, max 1,5Мб)'),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=xwear.utils.UploadToPath('banner', 'slide'), validators=[xwear.validators.ImageValidator(max_mb=2.0, min_height=630, min_width=1540)], verbose_name='Изображение (min 1540x630, max 2Мб)'),
        ),
    ]
