# Generated by Django 5.2.8 on 2026-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0008_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='actual_sizes',
            field=models.ManyToManyField(related_name='variants', through='xwear.ProductSize', to='xwear.size', verbose_name='Размеры'),
        ),
    ]
