# Generated by Django 5.2.8 on 2026-03-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0008_alter_sliderbanner_options_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='singular_name',
            field=models.CharField(blank=True, default='', help_text='Оставьте пустым, если совпадает с основным названием или не требуется', max_length=30, verbose_name='Название (ед. ч.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(default='', max_length=255, verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы взять имя из категории', max_length=50, verbose_name='Название товара'),
        ),
    ]
