# Generated by Django 5.2.8 on 2026-04-27 20:14

import xwear.utils
import xwear.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0009_productvariant_actual_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['size'], 'verbose_name': 'Размер и цена', 'verbose_name_plural': 'Размеры и цены'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=xwear.utils.UploadToPath('products', use_category_subdir=True), validators=[xwear.validators.ImageValidator(max_mb=1.5, min_height=600, min_width=500)], verbose_name='Фото (min 500x600, max 1,5Мб)'),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='image',
            field=models.ImageField(upload_to=xwear.utils.UploadToPath('banner', 'slide'), validators=[xwear.validators.ImageValidator(max_mb=2.0, min_height=630, min_width=1540)], verbose_name='Изображение (min 1540x630, max 2Мб)'),
        ),
    ]
