# Generated by Django 5.2.8 on 2026-03-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0009_category_singular_name_product_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='xwear.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Оставьте пустым, для автогенерации из категории', max_length=50, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Оставьте пустым для автогенерации', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='article',
            field=models.CharField(blank=True, help_text='Оставьте пустым для автогенерации (BRAND-CAT-ID-RANDOM)', max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
