# Generated by Django 5.2.8 on 2026-03-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0010_alter_product_category_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Оставьте пустым, для автогенерации из категории', max_length=50, verbose_name='Вид товара'),
        ),
    ]
