# Generated by Django 5.2.8 on 2026-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0010_alter_productsize_options_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderbanner',
            name='link',
        ),
        migrations.AddField(
            model_name='sliderbanner',
            name='links',
            field=models.JSONField(blank=True, default=list, verbose_name='Ссылки'),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок слайда'),
        ),
    ]
