# Generated by Django 5.2.8 on 2026-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0011_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
    ]
