# Generated by Django 5.2.8 on 2026-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0011_remove_sliderbanner_link_sliderbanner_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderbanner',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок слайда'),
        ),
    ]
