# Generated by Django 5.2.8 on 2026-05-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0012_alter_sliderbanner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderbanner',
            name='layout_links',
            field=models.CharField(choices=[('auto', 'Автоматически (1 ссылка — снизу по центру, более 1 — слева)'), ('bottom_center', 'Снизу по центру'), ('left_column', 'Слева под заголовком')], default='auto', max_length=50, verbose_name='Расположение ссылок'),
        ),
        migrations.AddField(
            model_name='sliderbanner',
            name='text_color',
            field=models.CharField(choices=[('light', 'Светлая (Белый текст)'), ('dark', 'Темная (Черный текст)')], default='dark', max_length=10, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='links',
            field=models.JSONField(blank=True, default=list, verbose_name='Ссылки (макс. 3)'),
        ),
    ]
