# Generated by Django 5.2.8 on 2026-03-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0012_alter_product_model_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товара'},
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='article',
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, help_text="Генерируется автоматически '[BRAND(2)][GENDER(1)][CAT_ID(3)]-[PROD_ID(5)][RAND(3)]'", max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Генерируется автоматически на основе вида, бренда и модели', verbose_name='Слаг'),
        ),
    ]
