# Generated by Django 5.2.8 on 2026-05-23 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0013_sliderbanner_layout_links_sliderbanner_text_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderbanner',
            name='layout_links',
        ),
        migrations.AddField(
            model_name='sliderbanner',
            name='content_width',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(90)], verbose_name='Ширина контента (%)'),
        ),
        migrations.AddField(
            model_name='sliderbanner',
            name='font_size_link',
            field=models.CharField(choices=[('1.6cqw', 'Мелкий'), ('1.8cqw', 'Средний'), ('2.0cqw', 'Крупный')], default='1.8cqw', max_length=10, verbose_name='Размер ссылок'),
        ),
        migrations.AddField(
            model_name='sliderbanner',
            name='font_size_title',
            field=models.CharField(choices=[('3.5cqw', 'Мелкий'), ('4.5cqw', 'Средний'), ('6.0cqw', 'Крупный')], default='4.5cqw', max_length=10, verbose_name='Размер заголовка'),
        ),
        migrations.AddField(
            model_name='sliderbanner',
            name='grid_layout',
            field=models.CharField(choices=[('top_left', 'Сверху слева'), ('top_center', 'Сверху по центру'), ('top_right', 'Сверху справа'), ('center_left', 'По центру слева'), ('center_center', 'По центру'), ('center_right', 'По центру справа'), ('bottom_left', 'Снизу слева'), ('bottom_center', 'Снизу по центру'), ('bottom_right', 'Снизу справа')], default='center_left', max_length=20, verbose_name='Расположение контента'),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='text_color',
            field=models.CharField(choices=[('light', 'Светлый (Белый текст)'), ('dark', 'Темный (Черный текст)')], default='dark', max_length=10, verbose_name='Цвет текста'),
        ),
    ]
