# Generated by Django 5.2.8 on 2026-03-27 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0014_alter_productsize_options_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название цвета')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('hex_code', models.CharField(default='#000000', help_text='Например: #FF0000 для красного', max_length=7, verbose_name='HEX код')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если это базовый цвет. Для других цветов выберите базовый товар.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_variations', to='xwear.product', verbose_name='Базовый товар (для связи цветов)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='xwear.color', verbose_name='Цвет'),
        ),
    ]
