# Generated by Django 5.2.8 on 2026-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0014_remove_sliderbanner_layout_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderbanner',
            name='font_size_link',
            field=models.CharField(choices=[('1.2cqw', 'Мелкий'), ('1.5cqw', 'Средний'), ('1.8cqw', 'Крупный')], default='1.8cqw', max_length=10, verbose_name='Размер ссылок'),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='font_size_title',
            field=models.CharField(choices=[('3.5cqw', 'Мелкий'), ('4.0cqw', 'Средне-мелкий'), ('4.5cqw', 'Средний'), ('5.0cqw', 'Средне-крупный'), ('5.5cqw', 'Крупный'), ('6.0cqw', 'Экстра-крупный')], default='4.5cqw', max_length=10, verbose_name='Размер заголовка'),
        ),
    ]
