# Generated by Django 5.2.8 on 2026-03-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0015_color_product_base_product_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code_2',
            field=models.CharField(blank=True, help_text='Заполните для двухцветных товаров (например, черно-белый)', max_length=7, null=True, verbose_name='Дополнительный HEX'),
        ),
        migrations.AddField(
            model_name='color',
            name='texture',
            field=models.ImageField(blank=True, help_text='Загрузите картинку (например, камуфляж). Если загружена, HEX-коды игнорируются.', null=True, upload_to='color_textures/', verbose_name='Текстура (Паттерн)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#000000', help_text='Обязательно для однотонных и двухцветных', max_length=7, verbose_name='Основной HEX-код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым, если это базовый цвет. Для других цветов выберите базовый товар.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='xwear.product', verbose_name='Базовый товар (для связи цветов)'),
        ),
    ]
