# Generated by Django 5.2.8 on 2026-05-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0015_alter_sliderbanner_font_size_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderbanner',
            name='font_size_link',
            field=models.CharField(choices=[('1.2cqw', 'Мелкий'), ('1.5cqw', 'Средний'), ('1.8cqw', 'Крупный')], default='1.5cqw', max_length=10, verbose_name='Размер ссылок'),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
