# Generated by Django 5.2.8 on 2026-07-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0016_alter_sliderbanner_font_size_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='final_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Размер'),
        ),
    ]
