# Generated by Django 5.2.8 on 2026-09-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0017_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
