# Generated by Django 5.2.8 on 2026-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0017_alter_color_options_color_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['order'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code_2',
            field=models.CharField(blank=True, default='', help_text='Заполните для двухцветных товаров (например, черно-белый)', max_length=7, verbose_name='Дополнительный HEX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='color',
            name='texture',
            field=models.ImageField(blank=True, default='', help_text='Загрузите картинку (например, камуфляж). Если загружена, HEX-коды игнорируются.', upload_to='color_textures/', verbose_name='Текстура (Паттерн)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='size',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
