# Generated by Django 5.2.8 on 2026-03-31 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0018_alter_color_options_alter_color_hex_code_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='xwear.color', verbose_name='Цвет'),
        ),
    ]
