# Generated by Django 5.2.8 on 2026-04-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0019_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text='Заполняется автоматически, если для текущей уже есть базовая модель.<br>Оставьте поле пустым, если это первая модель в серии (станет базовой).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='xwear.product', verbose_name='Базовая модель (для связи цветов)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='xwear.brand', verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
    ]
