# Generated by Django 5.2.8 on 2026-04-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwear', '0020_alter_product_base_product_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text='Заполняется автоматически, если для текущей уже есть базовая модель.<br>Оставьте поле пустым, если это первая модель в серии (станет базовой).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='xwear.product', verbose_name='Базовая модель (для связи цветов)'),
        ),
    ]
