# Generated by Django 5.2.8 on 2026-02-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuppoint',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон ПВЗ'),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='work_schedule',
            field=models.CharField(default='Пн-Вс 10:00-21:00', help_text='Напр: Пн-Пт 10:00-22:00, Сб-Вс 10:00-20:00', max_length=255, verbose_name='Режим работы'),
        ),
    ]
