# Generated by Django 5.2.8 on 2026-02-18 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('xwear', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xwear.productsize', verbose_name='Товар и размер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(default='', max_length=10, verbose_name='Размер'),
            preserve_default=False,
        ),
    ]
