# Generated by Django 5.2.8 on 2026-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_product_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Онлайн картой'), ('upon_receipt', 'При получении')], default='online', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
