# Generated by Django 5.2.8 on 2026-02-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free_delivery_active', models.BooleanField(default=True, verbose_name='Активировать бесплатную доставку')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Порог бесплатной доставки')),
                ('delivery_info', models.TextField(default='Доставка осуществляется курьером в пределах города. При заказе от 1000 руб. — бесплатно.', verbose_name='Информация о доставке')),
                ('payment_info', models.TextField(default='Оплата осуществляется при получении заказа картой либо наличными.', verbose_name='Информация об оплате')),
            ],
            options={
                'verbose_name': 'Условия доставки и оплаты',
                'verbose_name_plural': 'Условия доставки и оплаты',
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='8-802-100-4777', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='support@xwear.by', max_length=254, verbose_name='Email')),
                ('tg_url', models.URLField(blank=True, verbose_name='Telegram (ссылка)')),
                ('vb_url', models.URLField(blank=True, verbose_name='Viber (ссылка)')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK (ссылка)')),
                ('ok_url', models.URLField(blank=True, verbose_name='Odnoklassniki (ссылка)')),
                ('ig_url', models.URLField(blank=True, verbose_name='Instagram (ссылка)')),
                ('schedule_days', models.CharField(default='Пн-Пт', max_length=100, verbose_name='Дни работы')),
                ('schedule_time', models.CharField(default='с 9:00 до 18:00', max_length=100, verbose_name='Время работы')),
                ('schedule_extra', models.CharField(default='Сб-Вс: Выходные', max_length=100, verbose_name='Выходные дни')),
            ],
            options={
                'verbose_name': 'Контакты и соцсети',
                'verbose_name_plural': 'Контакты и соцсети',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Юридический документ',
                'verbose_name_plural': 'Юридические документы',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город и доставка', 'verbose_name_plural': 'Города и доставка'},
        ),
    ]
