# Generated by Django 5.2.8 on 2026-04-14 12:53

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_updated_at_alter_document_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О нас', max_length=50, verbose_name='Заголовок')),
                ('content', django_quill.fields.QuillField(verbose_name='Содержимое')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': "Страница 'О нас'",
                'verbose_name_plural': "Страница 'О нас'",
            },
        ),
    ]
