# Generated by Django 5.2.8 on 2026-07-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsettings',
            name='ok_url',
        ),
    ]
