# Generated by Django 5.2.8 on 2026-02-21 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_remove_user_first_name_remove_user_last_name_and_more'),
        ('orders', '0002_remove_cartitem_product_cartitem_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='pickup', max_length=20, verbose_name='Способ получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.TextField(verbose_name='Адрес доставки / ПВЗ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('paid', 'Оплачен'), ('ready', 'Готов к получению'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='processing', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес (улица, дом)')),
                ('working_hours', models.CharField(help_text='Напр: Будни 9:00-22:00, Сб-Вс 10:00-20:00', max_length=255, verbose_name='Время работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='accounts.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.pickuppoint', verbose_name='Пункт выдачи'),
        ),
    ]
